### ISSUE TITLE
Which version of Connext DDS is used/supported in ROS 2

### ISSUE THREAD

**Issue by firesurfer** [ros2/rmw_connext#158]
Due to problems with Opensplice I'm evaluating other DDS implementations.

I took a closer look at https://www.rti.com/products/ .
There are several versions of Connext DDS like Professional, Secure, Micro, Cert. 
Which of them is supported with ros 2 ?

As far as i can see rti connext is available for raspberry pis. ( https://community.rti.com/content/forum-topic/howto-run-rti-connext-dds-raspberry-pi )
Do you know of someone who already tried to run ROS 2 with rit connext on a raspberry pi?

**Comment by dirk-thomas** [comment]
We use the professional version for local testing and CI.

We haven't heard from anyone using connect on a raspberry pi.

**Comment by dirk-thomas** [comment]
I guess this has been answered so I will close the ticket.
