### ISSUE TITLE
use a heuristic to determine whether or not to use asynchronous publishing

### ISSUE THREAD

**Issue by wjwwood** [ros2/rmw_connext#190]
See: https://github.com/ros2/rmw_connext/pull/183#issue-162256750

The proposal from the linked pull request would be, use synchronous publishing:
- if the reliability is `BEST_EFFORT` (type bounded or unbounded)
- if the reliability is `RELIABLE` and the type is bounded and the maximum size is less than `MAX_SYNC_PAYLOAD`

Where `MAX_SYNC_PAYLOAD` is some maximum size that can be used without asynchronous publishing.

Use asynchronous publishing:
- if the reliability is `RELIABLE` and the type is bounded and the maximum size is more than `MAX_SYNC_PAYLOAD`
- if the reliability is `RELIABLE` and the type is unbounded (has no maximum size)

Something else to consider is whether or not messages with unbounded size can always be published with synchronous publishing, even with reliability as `BEST_EFFORT`.

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
