### ISSUE TITLE
Do something about name length limits

### ISSUE THREAD

**Issue by gerkey** [ros2/rmw_connext#193]
While working on ros2/rclcpp#233, it was discovered that connext can throw an error like this when trying to create a parameter service client:

```
PRESContentFilteredTopic_createFilterProperty:!copy content filtered property "filter expression" field: reached maximum length for content filter property (current length: 262, max. length: 256). Please consider increasing contentfilter_property_max_length parameter under participant's resource limits.
PRESContentFilteredTopic_associateReader:!copy sequence for content filtered property data
DDS_Subscriber_create_datareader_disabledI:ERROR: Failed to associate reader and content filtered topic
DDSDataReader_impl::create_disabledI:!create reader
DDSDataReader_impl::createI:!create reader
DDSDomainParticipant_impl::create_datareader:ERROR: Failed to create datareader
initialize:!create DataReader
connext::details::EntityUntypedImpl::initialize:!failed (see previous errors)
```

In this case, the node name was `test_parameters_local_synchronous_repeated` and the error above was produced when trying to create the `test_parameters_local_synchronous_repeated__get_parameter_types` client during the construction of a `SyncParametersClient`, which in turn constructs an `AsyncParametersClient`, which creates various clients. The service name is only 63 characters long, so presumably there's something else going on that's creating a filter expression that's 262 characters long.

For now, I'm working around the problem in the test by shortening the node name (to `test_parameters_local_synch_repeated`).

I don't know much about the name handling in DDS generally or connext specifically, so I'm starting by flagging this as an issue. It could be that the fix is in system configuration, not code.

**Comment by mikaelarguedas** [comment]
This is not an issue anymore
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3173)](http://ci.ros2.org/job/ci_linux/3173/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=514)](http://ci.ros2.org/job/ci_linux-aarch64/514/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2539)](http://ci.ros2.org/job/ci_osx/2539/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3235)](http://ci.ros2.org/job/ci_windows/3235/)
