### ISSUE TITLE
[connext_dynamic] finish support for wait_for_service

### ISSUE THREAD

**Issue by wjwwood** [ros2/rmw_connext#203]
Currently local changes to publishers and subscriptions are reflected in Connext dynamic, but not local changes to service clients and service servers, and so `rmw_service_server_is_available()` is still disabled for Connext dynamic (but not for Connext static):

https://github.com/ros2/rmw_connext/blob/8ad74fb18647fb39a7866c70984411b1b1dbb2d8/rmw_connext_dynamic_cpp/src/functions.cpp#L2333-L2335

This can be considered follow on work from: https://github.com/ros2/rmw_connext/issues/168

**Comment by wjwwood** [comment]
Tests that are disabled because of this: https://github.com/ros2/rcl/commit/596c0ec9faaa81cb4ba9dc064c27ba340412c023#diff-e4167ceebe2946426e927f55e4392af4R65

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
