### ISSUE TITLE
Testing for Beta2 coverage demo_nodes_cpp parameter tools are not working correctly on Windows

### ISSUE THREAD

**Issue by tfoote** [ros2/rmw_connext#233]
I am running the parameter nodes in demo_nodes_cpp and under connext they are not working correctly on Windows. They appear to be hanging. The events executables provide some output after the Ctrl-C but not the full equivalent of the fastrtps runs. I've waited 30+ seconds and it still responds quickly immediately after the Ctrl-C.

Output of events after Ctrl-C:
![parameter_events_after_ctrlc_sync](https://user-images.githubusercontent.com/447804/27666862-99ac6a98-5c2b-11e7-8e53-5de58a3c9524.gif)
Async version: 
![parameter_events_after_ctrlc](https://user-images.githubusercontent.com/447804/27666863-99ac9356-5c2b-11e7-9aea-c12c06e0f469.gif)
Simple set and get just hangs:
![set_and_get_parameters_connext](https://user-images.githubusercontent.com/447804/27666860-99a65b6c-5c2b-11e7-925b-7bf42570f40a.gif)
For reference fastrtps running the same sample in the same workspace:
![set_and_get_parameters_fastrtps](https://user-images.githubusercontent.com/447804/27666861-99ab3510-5c2b-11e7-817f-d3330cf524fd.gif)

**Comment by tfoote** [comment]
I can get the following errors if I run parameter_list side by side simultaneously. This might be the different impelementations. Did we ever homogenize the parameter implementation?

```
C:\dev\ros2>ros2 run demo_nodes_cpp list_parameters
RTI Data Distribution Service Evaluation License issued to OSRF - OSRF01 dthomas@osrfoundation.org For non-production use only.
Expires on 05-may-2018 See www.rti.com for more information.
PRESParticipant_getLocalOrRemoteParticipantShmemTransportCompatibility:!goto key remoteParticipant
PRESPsService_linkToLocalWriter:!getLocalOrRemoteParticipantShmemTransportCompatibility
PRESPsService_onLinkToLocalEndpointEvent:!create linkToLocalWriter
PRESParticipant_getLocalOrRemoteParticipantShmemTransportCompatibility:!goto key remoteParticipant
PRESPsService_linkToLocalWriter:!getLocalOrRemoteParticipantShmemTransportCompatibility
PRESPsService_onLinkToLocalEndpointEvent:!create linkToLocalWriter
PRESParticipant_getLocalOrRemoteParticipantShmemTransportCompatibility:!goto key remoteParticipant
PRESPsService_linkToLocalWriter:!getLocalOrRemoteParticipantShmemTransportCompatibility
PRESPsService_onLinkToLocalEndpointEvent:!create linkToLocalWriter
signal_handler(2)
```

![parameter_list_side_by_side](https://user-images.githubusercontent.com/447804/27667051-d3134788-5c2c-11e7-9133-490541cb0964.gif)

**Comment by tfoote** [comment]
ros2param has a different error:
```
C:\dev\ros2>ros2 run demo_nodes_cpp ros2param list add_two_ints_server
RTI Data Distribution Service Evaluation License issued to OSRF - OSRF01 dthomas@osrfoundation.org For non-production use only.
Expires on 05-may-2018 See www.rti.com for more information.
Timed out trying to list parameters: 10 seconds

C:\dev\ros2>
```

**Comment by dirk-thomas** [comment]
I tried to run all executables you mentioned (`parameter_events`, `parameter_events_async`, `set_and_get_parameters`, `list_parameters`) with Connext and all of them worked fine for me. I used a from-source build from on of the Jenkins nodes.

Please try to reproduce the problem from a fresh build and provide more information.

**Comment by tfoote** [comment]
Closing this as I can't reproduce today with an updated tree.
