### ISSUE TITLE
refactor rmw_connext_dynamic_cpp functions file

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rmw_connext#241]
Connext Dynamic should be refactored similarly to `rmw_connext_shared_cpp` and `rmw_connext_cpp`

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
