### ISSUE TITLE
catch error before nullptr access segfault 

### ISSUE THREAD

**Issue by serge-nikulin** [ros2/rmw_connext#246]
## Bug report

**Required Info:**

- Operating System: Windows 10
  - 
- Installation type: from source
  - 
- Version or commit hash: 188147a0428d199a1924764fa00df177549b6149
  - 
- DDS implementation: RTI Connext
  - 
- Client library (if applicable): N/A
  - 

#### Steps to reproduce issue
 Visual code inspection
```

```

#### Expected behavior
Return value of _DataReader::narrow call should be checked for nullptr
#### Actual behavior
rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em(167): no check
rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em(251): no check
rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em(279): [OK, see this commit ](https://github.com/ros2/rmw_connext/commit/9ff32755d16088c432c541477bc158dfe5a2a255)
rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em(439): no check

#### Additional information
In my previous company I have seen RTI Connext fails on this call. I highly recommend to test all returned pointers for NULL.

----
#### Implementation considerations
Please repeat this fix for all narrow calls:
https://github.com/ros2/rmw_connext/commit/9ff32755d16088c432c541477bc158dfe5a2a255

**Comment by dirk-thomas** [comment]
These cases should indeed be catched. Thanks for pointing it out.

Please consider to provide a pull request to improve this.

**Comment by serge-nikulin** [comment]
Why enhancement and not a bug?

**Comment by serge-nikulin** [comment]
@dejanpan, FYI

**Comment by dirk-thomas** [comment]
I labeled it "enhancement" since it is currently not resulting in any problems as far as we know. You can argue that it should have been written "defensive" in the first place (which I agree with).

**Comment by serge-nikulin** [comment]
Sorry about that, in my previous company all unchecked pointers were treated as compilation errors.

**Comment by serge-nikulin** [comment]
Pull request https://github.com/ros2/rmw_connext/pull/247

**Comment by dirk-thomas** [comment]
I will close this since it was addressed by #247.

@serge-nikulin If you include the following text in your PR it will automatically close this issue when the PR gets merged:

> Fixes #246
