### ISSUE TITLE
Several function calls are not checked for returns / Sequence lengths are not checked

### ISSUE THREAD

**Issue by dejanpan** [ros2/rmw_connext#278]
## Bug report

1. Several function calls are not checked for returns: see here https://github.com/ros2/rmw_connext/search?utf8=%E2%9C%93&q=return_loan&type=

1. Sequence lengths are not checked before accessed: https://github.com/ros2/rmw_connext/search?utf8=%E2%9C%93&q=DDS_SampleInfo+%26+sample_info+%3D+sample_infos%5B0%5D%3B&type=

I am running out of time to fix now but can do next month if noone else comes to it.

**Comment by dejanpan** [comment]
If someone comes to fix this, here would be another fix to be made. Return value of type support getter is not checked and callback pointer is not checked too.
1. https://github.com/ros2/rmw_connext/blob/master/rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em#L171
1. https://github.com/ros2/rmw_connext/blob/master/rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em#L389
1. https://github.com/ros2/rmw_connext/blob/master/rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em#L411

The code could be something like this:
```cpp
const rosidl_message_type_support_t * rosidl_message_type_support_ptr =
      ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(rosidl_typesupport_connext_c, @(field.type.pkg_name), msg, @(field.type.type))();
    if (rosidl_message_type_support_ptr == NULL)
    {
      throw std::runtime_error("rosidl_message_type_support_ptr == NULL");
    }
    const message_type_support_callbacks_t * @(field.type.pkg_name)__msg__@(field.type.type)__callbacks =
      static_cast<const message_type_support_callbacks_t *>(rosidl_message_type_support_ptr->data);
    if (@(field.type.pkg_name)__msg__@(field.type.type)__callbacks == NULL)
    {
      throw std::runtime_error("@(field.type.pkg_name)__msg__@(field.type.type)__callbacks == NULL");
    }
```

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
