### ISSUE TITLE
Add support for services for Connext API

### ISSUE THREAD

**Issue by wjwwood** [ros2/rmw_connext#3]
Acceptance Criteria:

- [x] Make use of ros_middleware_interface service API

**Comment by esteve** [comment]
@dirk-thomas @tfoote @wjwwood this ticket depends on a bunch of PRs, when you have a moment, I'd appreciate feedback for the remaining ones.

Thanks.

**Comment by dirk-thomas** [comment]
Beside the two small comments they LGTM.

**Comment by wjwwood** [comment]
I just reviewed the four pr's, lgtm +1
