### ISSUE TITLE
Performance issues with large data

### ISSUE THREAD

**Issue by deeplearningrobotics** [ros2/rmw_connext#302]
I used this tool https://github.com/ApexAI/performance_test to compare performance of _rmw_connext_ and _rmw_fastrtps_.

While performance seems ok with small data _rmw_connext_  does not properly work with large data.
It fails at sending 50 4Mb samples per second while _rmw_fastrtps_ can handle 500 samples per second.

This is **not** a problem with Connext Pro itself as I was using RTIs tool to verify proper performance( https://community.rti.com/downloads/rti-connext-dds-performance-test). 

All tests were done using Bouncy following the instructions from here: 
https://github.com/ros2/ros2/wiki/Linux-Development-Setup

**Results for 4Mb PointClound @ 50 Hz:**
Fastrtps Best Effort:
[log_PointCloud4m_19-09-2018_16-05-02.pdf](https://github.com/ros2/rmw_connext/files/2400841/log_PointCloud4m_19-09-2018_16-05-02.pdf)
Connext Pro Best Effort:
[log_PointCloud4m_19-09-2018_14-30-57.pdf](https://github.com/ros2/rmw_connext/files/2400829/log_PointCloud4m_19-09-2018_14-30-57.pdf)
Connext Pro Reliable:
[log_PointCloud4m_19-09-2018_14-34-17.pdf](https://github.com/ros2/rmw_connext/files/2400834/log_PointCloud4m_19-09-2018_14-34-17.pdf)

**Results for 4Mb PointClound @ 500 Hz:**
Fastrtps Best Effort:
[log_PointCloud4m_19-09-2018_16-07-02.pdf](https://github.com/ros2/rmw_connext/files/2400852/log_PointCloud4m_19-09-2018_16-07-02.pdf)
Connext Pro Best Effort:
[log_PointCloud4m_19-09-2018_14-50-57.pdf](https://github.com/ros2/rmw_connext/files/2400856/log_PointCloud4m_19-09-2018_14-50-57.pdf)

To run a full performance investigation which also reproduces the results here you can run 
`python src/performance_test/performance_test/helper_scripts/run_experiment.py` as described here: https://github.com/ApexAI/performance_test

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
