### ISSUE TITLE
get_datareader_qos should use DDSSubscriber and get_datawriter_qos should use DDSPublisher

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#318]
#### Feature description
The get_datawriter_qos and get_datareader_qos use a RTI Connext DDS API extension to retrieve the default datareader/datawriter QoS from the DDSDomainParticipant. According to the DDS specification the datareader QoS should be retrieved from DDSSubscriber and datawriter QoS shoiuld be retrieved from DDSPublisher. 

#### Implementation considerations
By using the RTI extension this code can break in the future.

https://github.com/ros2/rmw_connext/blob/99790fa77e76021a62574e2537bc1e30701fd452/rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/qos.hpp#L30

**Comment by lij-oci** [comment]
@jwillemsen Thanks for the information.

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
