### ISSUE TITLE
Downcasting DDS entities should use dynamic_cast/narrow

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#329]
#### Feature description
For downcasting DDS entities to a specific DDS entity dynamic_cast should be used, not static_cast. Even better is to use the generated narrow operations. Something for after #328 

#### Implementation considerations
Not sure whether there are code guidelines not to use dynamic_cast

**Comment by jwillemsen** [comment]
Please assign to me

**Comment by allenh1** [comment]
I'm not so sure you want to `dynamic_cast` these, especially in cases like [this, from the aforementioned PR](https://github.com/ros2/rmw_connext/blob/8fc950a4d71189037d9d74bfa0bde36796f0f234/rmw_connext_cpp/src/get_participant.cpp#L31) where `node->data` is a `void *`.

What's the specific inheritance you are looking at here?

**Comment by jwillemsen** [comment]
Inheritance between DDS based interfaces, will make a PR tomorrow
