### ISSUE TITLE
Remove reader as argument name

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#331]
When removing reader as argument name the `(void) reader;` can be removed

https://github.com/ros2/rmw_connext/blob/99790fa77e76021a62574e2537bc1e30701fd452/rmw_connext_cpp/include/rmw_connext_cpp/connext_static_subscriber_info.hpp#L46

**Comment by clalancette** [comment]
I don't really agree; if we remove that `(void) reader`, then we'll get a compiler warning about an unused argument.  Why do you think it can be removed?

**Comment by jwillemsen** [comment]
```
virtual void on_subscription_matched(
  DDSDataReader *,
  const DDS_SubscriptionMatchedStatus & status)
{
    current_count_ = status.current_count;
}
```

**Comment by clalancette** [comment]
Oh sure.  That is a purely style thing; the generated code won't be any different.  We generally follow the Google C++ [style guide](https://google.github.io/styleguide/cppguide.html), which does agree with your style.  But we have quite a few instances of the C-style `(void) reader`, so I'm not sure this really warrants a change.

**Comment by jwillemsen** [comment]
Just something I found when working on rmw_opendds but given the several of pull request already pending I don't want to add more, this one could cause merge conflicts

**Comment by jwillemsen** [comment]
Please assign to me
