### ISSUE TITLE
DDS_DURATION_INFINITE is a RTI specific DDS type

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#333]
#### Feature description
DDS_DURATION_INFINITE is a RTI specific macro, to initialize a Duration_t to infinite sec/nsec should be set separately

#### Implementation considerations
DDS_DURATION_INFINITE (or DDS::DURATION_INFINITE) is RTI specific so should not be used to simplify porting rmw code between vendors

**Comment by jwillemsen** [comment]
Please assign to me

**Comment by sloretz** [comment]
fixed by #335
