### ISSUE TITLE
Use RCUTILS_LOG_ERROR_NAMED instead of fprintf

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#344]
#### Feature description
Use RCUTILS_LOG_ERROR_NAMED instead of fprintf, see #339

**Comment by jwillemsen** [comment]
This should be checked for all rmw related libraries, lot of code is copied between them, so probably they all have printf statements for logging

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
