### ISSUE TITLE
received WStrings messages from FastRTPS incorrect

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_connext#364]
## Bug report

**Required Info:**

- Operating System:
  - macOS
- Installation type:
  - source
- Version or commit hash:
  - master branch after merging the `WStrings` test: https://github.com/ros2/rosidl/issues/388#issuecomment-513290450
- DDS implementation:
  - FastRTPS publishing, Connext 5.3.1 subscribing
- Client library (if applicable):
  - any

#### Steps to reproduce issue
Enable the test which publishes a `WStrings` message with non-ASCII characters using FastRTPS and subscribes using Connext by removing the following condition which skips the test atm: https://github.com/ros2/system_tests/pull/377/commits/49cdb2f57a557590a59ed6680a8682cd48571f71#diff-02dc43db6f966560e7ee414c298df21eR193

#### Expected behavior

The test passes as it does with all other cross-vendor combinations.

#### Actual behavior

The test fails because the message returned by Connext doesn't match the expectation. The members which have default values with non-ASCII values are not terminated correctly. E.g. the value of the [wstring_value_default2](https://github.com/ros2/test_interface_files/blob/4a20196a92194ee4111f3877eaa975bcbfa98f8d/msg/WStrings.msg#L3) member doesn't end after 12 characters but is actually 19 characters long including the value of the following member `wstring_value_default3`.

#### Additional information

The test passes in all other variations:
* all platforms: FastRTPS -> FastRTPS, Connext -> Connext, Connext -> FastRTPS
* FastRTPS -> Connext when the subscriber side is not running on macOS

**Comment by dirk-thomas** [comment]
@neil-rti Maybe you can provide some feedback if this is a known issue.

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
