### ISSUE TITLE
Gazebo ros plugins fail to create topic when using rmw_connext

### ISSUE THREAD

**Issue by crdelsey** [ros2/rmw_connext#372]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source (latest ROS2 and Gazebo ros pkgs as of Monday 14 Oct 2019)
- Version or commit hash:
  - [2019-10-14-09-01-15.repos.txt](https://github.com/ros2/rmw_connext/files/3731920/2019-10-14-09-01-15.repos.txt)
- DDS implementation:
  - RTI Connext 5.3.1
- Client library (if applicable):
  - 

#### Steps to reproduce issue

Launch gzserver with the ROS plugin, while using RTI Connext as DDS
```
gzserver --verbose -s libgazebo_ros_init.so
```

#### Expected behavior

It launches succesfully

#### Actual behavior

It terminates immediately with the following error.

```
DDS_Topic_createI:!create presentation topic
DDSTopic_impl::createI:!create topic
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  could not create publisher: failed to create topic, at /home/crdelsey/src/ros_dev_workspace/ros2_ws/src/ros2/rmw_connext/rmw_connext_cpp/src/rmw_publisher.cpp:205, at /home/crdelsey/src/ros_dev_workspace/ros2_ws/src/ros2/rcl/rcl/src/rcl/publisher.c:172
```

#### Additional information

It fails this way for me approximately 50% of the time.

Originally reported in ros-planning/navigation2#915

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
