### ISSUE TITLE
a subscriber of RTI native application can't receive messages from ros2 publisher

### ISSUE THREAD

**Issue by iuhilnehc-ynos** [ros2/rmw_connext#474]
I don't know whether this is an issue or not, but it seems that a ros2 subscriber can receive messages from a publisher of RTI native application. https://github.com/iuhilnehc-ynos/rti_application_and_ros2_communication/blob/main/README.md

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - foxy
- DDS implementation:
  - rmw_connext_cpp
- Client library (if applicable):
  - rcl

#### Steps to reproduce issue

1. run a RTI native subscriber example

```
$ git clone https://github.com/iuhilnehc-ynos/rti_application_and_ros2_communication.git
$ cd rti_application_and_ros2_communication
$ source /opt/rti.com/rti_connext_dds-5.3.1/setenv_ros2rti.bash
$ make -f makefile_string_x64Linux3gcc5.4.0
$ ./objs/x64Linux3gcc5.4.0/string_subscriber
```
NOTE: Sorry for only providing ubuntu20.04 sample.

2. run ros2 client publisher

```
$ source /opt/ros/foxy/setup.bash
$ RMW_IMPLEMENTATION=rmw_connext_cpp ros2 topic pub chatter std_msgs/String 'data: hello world'
```

#### Expected behavior

the RTI native subscriber example can receive messages from ros2 publisher

#### Actual behavior

the RTI native subscriber example can't receive messages from ros2 publisher

#### Additional information

BTW: This case is working if I use other RMW_IMPLEMENTATION(rmw_fastrtps_cpp) and native examples(FastDDS).

**Comment by clalancette** [comment]
Communication between "native" DDS networks and ROS 2 is a long-standing feature request, but we haven't had time to look into the issues and make it work reliably.  Patches to improve it would be welcome, of course.

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
