### ISSUE TITLE
fix returning from rmw_wait while any samples have not been taken yet: For Services

### ISSUE THREAD

**Issue by tfoote** [ros2/rmw_connext#67]
Parallel to https://github.com/ros2/rmw_connext/pull/62 but for serices.

blocking https://github.com/ros2/system_tests/pull/14

**Comment by dirk-thomas** [comment]
Is this not already implemented in #66?

**Comment by tfoote** [comment]
Sorry #66 didn't get referenced into the ros2/system_tests#14 thread
