### ISSUE TITLE
Client and service do not exchange messages

### ISSUE THREAD

**Issue by esteve** [ros2/rmw_connext#96]
See ros2/rclcpp#95

* `add_two_ints_server__rmw_connext_cpp` / `add_two_ints_client__rmw_connext_cpp` do not exchange any messages

**Comment by esteve** [comment]
Testing this again, it seems this issue does not happen consistently.

**Comment by jacquelinekay** [comment]
CI for the set of branches connected to this issue looks fine:

http://ci.ros2.org/job/ros2_batch_ci_linux/344/
http://ci.ros2.org/job/ros2_batch_ci_osx/263/
http://ci.ros2.org/job/ros2_batch_ci_windows/398/
